### ISSUE TITLE
i18n-js compatibility

### ISSUE THREAD

**Issue by IngoAlbers** [attilahorvath/i18n-globals#10]
When I use this gem in addition to [i18n-js](https://github.com/fnando/i18n-js) it doesn't work.
It will always say `[missing %{translation} value]` for translations that I get in the javascript. Everywhere else it will work fine.
Do you have an idea on how to make it work? I would also like to contribute if you could point me in the right direction.

**Comment by attilahorvath** [comment]
That library is basically an indepedent JavaScript reimplementation of the Ruby I18n gem, so extending just the Ruby code (which is what this gem does) won't affect i18n-js. That's why you're not seeing any changes in its behaviour when you use this gem.

If you want to have similar global variable functionality on the JS side, you'd have to port the changes we've made in this gem to their JS code. This should be relatively simple enough though, so I'll see if I have time to experiment with that. I could see the value in releasing those extensions as a separate gem, such as i18n-js-globals to be used in tandem with this one.

By the way I did some investigating, the error you're seeing comes from https://github.com/fnando/i18n-js/blob/master/app/assets/javascripts/i18n.js#L581 so if you want to give it a shot coding it yourself, I'd suggest to start digging there (I assume the `missingPlaceholder` function could be extended to try and read values from a `globals` hash).

Hope this helps.

**Comment by IngoAlbers** [comment]
Thank you for the insightful answer. I'll have a look.
Since this is not an issue with this project then I guess we can close the issue.

**Comment by IngoAlbers** [comment]
Just for your info my short term solutions is this. I added this line to the `application.html`.

``` javascript
I18n.globals = <%= I18n.config.globals.to_json.html_safe %>;`
```

And then I extended the I18n-js gem at your specified location and added this condition:

``` javascript```
} else if (I18n.globals[name]) {
    value = I18n.globals[name];
}
```

Thanks again for the help.

**Comment by attilahorvath** [comment]
Glad to see you could get it working with just a few lines of code.

It could be worthwhile to package it in a separate gem though to make it easier to set up with new projects. I'll look into it when I get some free time.
